### ISSUE TITLE
Export fails with empty spaces in Nintendo 64 media paths

### ISSUE THREAD

**Issue by praveensharma** [spektor56/PegasusExportPlugin#6]
Looks like something is going wrong with the exporter when attempting to export my nintendo 64 metadata and media. Other platforms are ok. I have tried removing media but it fails on all media.

(Inner Exception)

Could not find a part of the path 'E:\Pegasus\Nintendo 64\media\1080 Snowboarding \boxFront.png'.

App:     LaunchBox
Version: 11.9
Type:    System.IO.DirectoryNotFoundException
Site:    Void CopyFile(System.String, System.String, Boolean)
Source:  System.IO.FileSystem

   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at PegasusExportPlugin.frmPegasusExport.<>c__DisplayClass4_2.<BtnExport_Click>b__20(IGrouping`2 gamePlatform) in C:\Users\l-bre\Source\Repos\spektor56\PegasusExportPlugin\PegasusExportPlugin\frmPegasusExport.cs:line 481
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()

(Outer Exception)

One or more errors occurred. (Could not find a part of the path 'E:\Pegasus\Nintendo 64\media\1080 Snowboarding \boxFront.png'.)

App:     LaunchBox
Version: 11.9
Type:    System.AggregateException
Site:    Void Run[TState](ReplicatableUserAction`1, System.Threading.Tasks.ParallelOptions, Boolean)
Source:  System.Threading.Tasks.Parallel

   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at PegasusExportPlugin.frmPegasusExport.<>c__DisplayClass4_1.<BtnExport_Click>b__2() in C:\Users\l-bre\Source\Repos\spektor56\PegasusExportPlugin\PegasusExportPlugin\frmPegasusExport.cs:line 519
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at PegasusExportPlugin.frmPegasusExport.BtnExport_Click(Object sender, EventArgs e) in C:\Users\l-bre\Source\Repos\spektor56\PegasusExportPlugin\PegasusExportPlugin\frmPegasusExport.cs:line 107
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Recent Log:

   4:34:03 PM Exception

**Comment by spektor56** [comment]
so launchbox says there's a file there but there is no actual file there.  Why is there a space at the end of "1080 Snowboarding "??

**Comment by spektor56** [comment]
should be fixed in latest version: https://github.com/spektor56/PegasusExportPlugin/releases/download/v1.9-alpha/PegasusExportPlugin.zip
